pipeline:
  backend:
    group: build
    image: golang
    commands:
      - go build
      - go test
  frontend:
    group: build
    image: alpine
    commands:
    - echo hola
    - echo mundo
  fr:
    image: alpine
    commands:
    - echo bonjour
    - echo monde
