pipeline:
  backend:
    group: build
    image: golang
    commands:
      - go build
      - go test
  frontend:
    group: build
    image: alpine
    commands:
    - echo hola
    - echo mundo
  publish:
    image: plugins/docker
    repo: octocat/hello-world
